image: "archlinux:latest"

pages:
  stage: deploy
  script:
    - pacman -Sy valadoc libgee --noconfirm
    - valadoc -o public --package-name=sfml sfml.vapi --use-svg-images --importdir documentation/sfml --import sfml --force
    - echo "Pages deployment job at ${CI_PAGES_URL}"
  
  artifacts:
    paths:
      - public
  only:
  - main

